version: '3.7'

services:
  web:
    build: .
    container_name: yii2_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - YII_ENV=dev
      - YII_DEBUG=1
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: yii2_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: yii2
      MYSQL_USER: yii2
      MYSQL_PASSWORD: yii2_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
